export const states = {
  AC: {
    name: "Acre",
    abbreviation: "AC",
    latitude: -8.77,
    longitude: -70.55,
  },
  AL: {
    name: "Alagoas",
    abbreviation: "AL",
    latitude: -9.71,
    longitude: -35.73,
  },
  AP: {
    name: "Amapá",
    abbreviation: "AP",
    latitude: 1.41,
    longitude: -51.77,
  },
  AM: {
    name: "Amazonas",
    abbreviation: "AM",
    latitude: -3.07,
    longitude: -61.66,
  },
  BA: {
    name: "Bahia",
    abbreviation: "BA",
    latitude: -12.96,
    longitude: -38.51,
  },
  CE: {
    name: "Ceará",
    abbreviation: "CE",
    latitude: -3.71,
    longitude: -38.54,
  },
  DF: {
    name: "Distrito Federal",
    abbreviation: "DF",
    latitude: -15.83,
    longitude: -47.86,
  },
  ES: {
    name: "Espírito Santo",
    abbreviation: "ES",
    latitude: -19.19,
    longitude: -40.34,
  },
  GO: {
    name: "Goiás",
    abbreviation: "GO",
    latitude: -16.64,
    longitude: -49.31,
  },
  MA: {
    name: "Maranhão",
    abbreviation: "MA",
    latitude: -2.55,
    longitude: -44.3,
  },
  MT: {
    name: "Mato Grosso",
    abbreviation: "MT",
    latitude: -12.64,
    longitude: -55.42,
  },
  MS: {
    name: "Mato Grosso do Sul",
    abbreviation: "MS",
    latitude: -20.51,
    longitude: -54.54,
  },
  MG: {
    name: "Minas Gerais",
    abbreviation: "MG",
    latitude: -18.1,
    longitude: -44.38,
  },
  PA: {
    name: "Pará",
    abbreviation: "PA",
    latitude: -5.53,
    longitude: -52.29,
  },
  PB: {
    name: "Paraíba",
    abbreviation: "PB",
    latitude: -7.06,
    longitude: -35.55,
  },
  PR: {
    name: "Paraná",
    abbreviation: "PR",
    latitude: -24.89,
    longitude: -51.55,
  },
  PE: {
    name: "Pernambuco",
    abbreviation: "PE",
    latitude: -8.38,
    longitude: -37.86,
  },
  PI: {
    name: "Piauí",
    abbreviation: "PI",
    latitude: -8.28,
    longitude: -43.68,
  },
  RJ: {
    name: "Rio de Janeiro",
    abbreviation: "RJ",
    latitude: -22.84,
    longitude: -43.15,
  },
  RN: {
    name: "Rio Grande do Norte",
    abbreviation: "RN",
    latitude: -5.22,
    longitude: -36.52,
  },
  RS: {
    nome: "Rio Grande do Sul",
    uf: "RS",
    latitude: -30.01,
    longitude: -51.22,
  },
  RO: {
    nome: "Rondônia",
    uf: "RO",
    latitude: -10.83,
    longitude: -63.34,
  },
  RR: {
    nome: "Roraima",
    uf: "RR",
    latitude: 1.99,
    longitude: -61.33,
  },
  SC: {
    nome: "Santa Catarina",
    uf: "SC",
    latitude: -27.33,
    longitude: -49.44,
  },
  SP: {
    nome: "São Paulo",
    uf: "SP",
    latitude: -23.55,
    longitude: -46.64,
  },
  SE: {
    nome: "Sergipe",
    uf: "SE",
    latitude: -10.57,
    longitude: -37.45,
  },
  TO: {
    nome: "Tocantins",
    uf: "TO",
    latitude: -10.25,
    longitude: -48.25,
  },
};
